apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-config
data:
  default.topic.partitions: "10"
  default.topic.replication.factor: "3" 
  bootstrap.servers: "kafka-serverless-kafka-bootstrap.eventing-demo.svc:9092"
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: kafka-broker 
  annotations:
    eventing.knative.dev/broker.class: Kafka 
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
