apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-pi-service
  labels:
    app: quarkus-pi-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-pi-service
  template:
    metadata:
      labels:
        app: quarkus-pi-service
    spec:
      containers:
        - name: quarkus-pi-service
          image: quay.io/rh_ee_ozimakov/quarkus-pi-service:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
              initialDelaySeconds: 3
              periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
              initialDelaySeconds: 3
              periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-pi-service
spec:
  selector:
    app: quarkus-pi-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080