name: Verify

on:
  push:
    branches:
      - 'main'


jobs:
  test-quarkus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build Quarkus service
        run: |
          cd ./quarkus-pi-service
          ./mvnw -B test

  test-springboot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build Spring Boot service
        run: |
          cd ./springboot-pi-service
          ./mvnw -B test