name: Release

on:
  push:
    branches:
      - 'feature/release-workflow'

jobs:
  build-quarkus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Quarkus image
        run: |
          cd ./quarkus-pi-service
          ./mvnw install -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
          docker tag runner/quarkus-pi-service:latest quay.io/rh_ee_ozimakov/quarkus-pi-service:latest
          docker push quay.io/rh_ee_ozimakov/quarkus-pi-service:latest

  build-springboot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Spring Boot image
        run: |
          cd ./springboot-pi-service
          ./mvnw -B install spring-boot:build-image
          docker tag springboot-pi-service:latest quay.io/rh_ee_ozimakov/springboot-pi-service:latest
          docker push quay.io/rh_ee_ozimakov/springboot-pi-service:latest
