name: Release

on:
  push:
    branches:
      - 'feature/release-workflow'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build pi-commons
        run: |
          cd pi-common
          ./mvnw -B install

#      - name: Build & push Spring Boot service image
#        run: |
#          cd ./springboot-pi-service
#          ./mvnw -B install spring-boot:build-image
#          docker tag springboot-pi-service:latest quay.io/rh_ee_ozimakov/springboot-pi-service:latest
#          docker push quay.io/rh_ee_ozimakov/springboot-pi-service:latest
          

      - name: Build & push Quarkus service image
        run: |
          cd ./quarkus-pi-service
          ./mvnw -B package -Pnative
          docker build -f src/main/docker/Dockerfile.native -t quay.io/rh_ee_ozimakov/quarkus-pi-service:latest
          docker push quay.io/rh_ee_ozimakov/quarkus-pi-service:latest
